function dydt = ODE_state(t, y, A, B, C, D, Q, R, xi)
delta = y(4) - y(5) - y(6);
E = 2*y(1) - y(2) - y(3);
alpha = -(delta*D*C*E/xi + B*delta + D*C*y(4))/(R + y(4)*D^2 + delta*E*D^2/xi);
h = (C + D*alpha)*E/xi;
dydt = [(2*A + 2*C*h + 2*(B + D*h)*alpha + (C+D*alpha)^2)*y(1) + 0.5*Q + 0.5*R*alpha^2 - 0.5*h^2*xi; ...
    (2*A + 2*C*h + 2*(B + D*h)*alpha)*y(2); ...
    (A + C*h + (B + D*h)*alpha)*y(3); ...
    (2*A + 2*C*h + C^2 + D*h*alpha + B*alpha + C*D*alpha)*y(4) + Q - h^2*xi; ...
    (2*A + 2*C*h + D*h*alpha + B*alpha)*y(5); ...
    (A + C*h)*y(6)];
end